### ISSUE TITLE
Backdrop container for input field and username label

### ISSUE THREAD

**Issue by DarwinsBuddy** [manilarome/the-glorious-lightdm-webkit2-theme#26]
1. Nice project, very cool theme!

2. When choosing a background it's often VERY hard (especially with the provided hex-input field) to pick a foreground-color harmonizing with the chosen background image, in a sense of readability.

Following suggestions occurred to me to improve this:
- Embed the input fields/labels a square container in it (probably with rounded corners and a configurable opacity) to create a higher contrast between the background image and the written text.
- Integrate a simple color picker for choosing colors and get rid of the Apply button to immediately see the results of your chosen color.

Still, big fan! Keep up the work and thanks for your contribution! :)

**Comment by eromatiya** [comment]
> Embed the input fields/labels a square container in it (probably with rounded corners and a configurable opacity) to create a higher contrast between the background image and the written text.

Yeah the contrast between input fields and the background image needs an improvement. My first plan was to add a `backdrop-filter: blur()`, but `webkit2gtk` doesn't support it (it uses a very old version of webkit). So yeah, it's recommended to use a blur filter to solve this issue because I don't really plan to change its ui (add a backdrop/square container) in the near future.

> Integrate a simple color picker for choosing colors and get rid of the Apply button to immediately see the results of your chosen color.

Sorry, but I don't really want to use a third party library. The theme's already bloated haha.

Thanks for the suggestion! :)
