### ISSUE TITLE
Window Manager Not Lauching

### ISSUE THREAD

**Issue by anshumansaini1** [manilarome/the-glorious-lightdm-webkit2-theme#34]
Every time I login to my desktop, instead of sending me to either i3 or MATE it sends me back to the Login screen.

**Comment by eromatiya** [comment]
Uhm I cannot reproduce this. Could you please send a log and more information like lightdm-webkit version, distro, and etc.? Please, also make sure to test a different lightdm-webkit themes and check `/usr/share/xsessions/`. Going back to login screen after logging in is somewhat not a lightdm theme problem, because it should throw an error message if there's one.

**Comment by anshumansaini1** [comment]
Im running Webkit2 on Void Linux, I just configured LightDM today. I'm going /usr/share/Xsession. I am running Bedrock Linux on top of Void, but I used Void's XBPS package manager. And I didn't get any error message.

**Comment by anshumansaini1** [comment]
I was able to fix the issue by setting session-wrapper to;
/etc/lightdm/Xsession & then rebooting the system. For some reason session wrapper was commented out and wasn't set to Xsessions.

**Comment by eromatiya** [comment]
Thanks for the info. Will add that to README. Thanks again!
